In [1]:
import numpy as np
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [2]:
ch_arr2=np.array(["Supervised","unsupervised","sEMI-supervised","reinforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [6]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [7]:
array1=np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [8]:
array1.dtype

dtype('int32')

In [9]:
char_arr.dtype

dtype('<U1')

In [10]:
low_arr.dtype

dtype('<U15')

In [15]:
array8=np.array([1,2,3,4,5],dtype='f')


In [16]:
array8

array([1., 2., 3., 4., 5.], dtype=float32)

In [17]:
array2conv=array8.astype('f')
array2conv

array([1., 2., 3., 4., 5.], dtype=float32)

In [18]:
array7conv=array2conv.astype('i')
array7conv

array([1, 2, 3, 4, 5], dtype=int32)

In [19]:
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [20]:
char_conv=char_arr.astype('i')
char_conv

ValueError: invalid literal for int() with base 10: 'a'

In [21]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [25]:
ars2=np.zeros(4)
ars2

array([0., 0., 0., 0.])

In [24]:
ars3=np.random.random(3)
ars3

array([0.87216902, 0.28823209, 0.49849049])

In [26]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [29]:
numzeros=np.zeros((3,2))
numzeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
dimones=np.ones((4,3,2))

In [33]:
dimones.ndim

3

In [34]:
#additon
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
addition=ar1+ar2
print("addition:\n",addition)

addition:
 [[ 6  8 10]
 [12 14 16]]


In [35]:
#subtraction
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
addition=ar1-ar2
print("addition:\n",addition)

addition:
 [[-4 -4 -4]
 [-4 -4 -4]]


In [36]:
#multiplication
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
addition=ar1*ar2
print("addition:\n",addition)

addition:
 [[ 5 12 21]
 [32 45 60]]


In [37]:
#division
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
addition=ar1/ar2
print("addition:\n",addition)

addition:
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [38]:
power=np.power(ar1,ar2)
print("power:\n",power)

power:
 [[       1       64     2187]
 [   65536  1953125 60466176]]


In [48]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])
result=array2d+array1d
result

array([[11, 22, 25],
       [14, 25, 28]])

In [49]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [50]:
a=np.random.randint(low=1,size=5)
a

array([0, 0, 0, 0, 0])

In [51]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[3, 3, 2],
       [2, 4, 4]])

In [52]:
np.concatenate([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
flatarr=ar1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [54]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [55]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3
